### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by eallum** [explosivo22/rinnaicontrolr-ha#32]
Entered email address, password and submitted. Received error "Unknown error occurred". 
How to determine what is the error?

![Screenshot 2022-11-15 204238](https://user-images.githubusercontent.com/37742109/202062592-5e6964d7-4aab-4c49-a304-a79f0a2d1e69.jpg)

**Comment by explosivo22** [comment]
You can try and put the following in your configuration file and then look for an error in your log

```
logger:
  logs:
    # log level for a custom component
    custom_components.rinnai: debug

    # log level for the `aiohttp` Python package
    aiorinnai: debug
```
